### ISSUE TITLE
Feature request: Report cached memory

### ISSUE THREAD

**Issue by jorpppp** [wbuchanan/StataOS#1]
Please update -sysresources- to report cached memory in addition to physical memory and swap space. This will allow Stata to check for available memory in the cache as well as in the free physical memory.

**Comment by wbuchanan** [comment]
@jorpppp it wouldn't be quite as difficult if I bump up the JVM to java 8.  It isn't the prettiest, but here's what it would look like:

```
. sysresources vm_stat

. ret li

macros:
       r(Pages_purged) : "1783139"
  r(Mach_Virtual_Memo
    ry_Statistics)     : "bytes"
               r(File) : "501488"
            r(Swapins) : "0"
    r(Pages_purgeable) : "518970"
  r(Pages_occupied_by
    _compressor)       : "679129"
  r(Pages_stored_in_c
    ompressor)         : "1182369"
       r(Pages_active) : "2192415"
           r(Pageouts) : "753"
           r(Swapouts) : "0"
       r(Compressions) : "5276753"
  r(Pages_reactivated) : "1366587"
         r(Pages_copy) : "10997653"
   r(Pages_wired_down) : "520353"
            r(Pageins) : "4018840"
    r(Anonymous_pages) : "2108845"
     r(Pages_inactive) : "196436"
  r(Pages_zero_filled) : "112774061"
         r(Pages_free) : "381211"
    r(Pages_throttled) : "0"
     r(Decompressions) : "3040666"
  r(Pages_speculative) : "221482"
                r(raw) : "Mach Virtual Memory Statistics: (page size of 4096 bytes)Pages free:                              381211.Pages active:                       .."
           r(clgroups) : "2, 4"
            r(pgroups) : "2, 4"
            r(cleaner) : "(^([\w _]{1,}+)(\W{1,}.*)$)"
             r(parser) : "((.*)(\s{1,}+)(.*))"
```

I can try to figure out a way to handle recasting numeric values to numbers that get returned in the macros but it definitely will be system dependent and will require the user to know what the command line interface commands are to get what they are looking for.

**Comment by wbuchanan** [comment]
@jorpppp This is squared away for Java 6 (at least to some rudimentary level) and ends up being a bit more flexible.  It looses platform independence (e.g., Windoze users will need to know the equivalent DOS commands), but can handle quite a bit more.  I'll probably change the handling of the `stdout` in the future to return the individual lines of output in their own macros without any attempt to clean/parse things, but this seemed like it would be the easier fit for the more immediate need.

**Comment by jorpppp** [comment]
Works great, thanks!

**Comment by wbuchanan** [comment]
@jorpppp Awsome.  Glad to hear it.  It made me start thinking about how to make it a bit more useful and I still need to figure out how to pass commands with option flags/arguments so people could do things like 

```
ps -ax | grep stata-mp
```

If they wanted to get the process ID for Stata and/or things like that.
